# Generated by Django 3.0.6 on 2020-05-31 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='名前')),
                ('phone', models.CharField(max_length=200, null=True, verbose_name='携帯番号')),
                ('email', models.CharField(max_length=200, null=True, verbose_name='メールアドレス')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='タグ名')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='商品名')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='価格')),
                ('category', models.CharField(choices=[('Indoor', 'インドア'), ('Out Door', 'アウトドア')], max_length=200, null=True, verbose_name='カテゴリー')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='商品説明')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日')),
                ('tags', models.ManyToManyField(to='accounts.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='注文日')),
                ('status', models.CharField(choices=[('Pending', '保留中'), ('Out for delivery', '配達中'), ('Delivered', '配達済み')], max_length=200, null=True, verbose_name='配達状況')),
                ('note', models.CharField(max_length=1000, null=True, verbose_name='メモ')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Customer', verbose_name='顧客')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Product', verbose_name='商品')),
            ],
        ),
    ]
